## Code written by Michael Vella
## 12/7/19
## Generates results from:
## Development and testing of a novel Killer-Rescue self-limiting 
## gene drive system in Drosophila melanogaster
## Authors: Sophia H. Webster, Michael R. Vella, and Maxwell J. Scott
  
## Must have KR_functions.R, KR_data.csv, and offprobs.rds in working directory

## experiment labels as follows:
## G80: Gal80 rescue only
## DG4: DSCP-Gal4 killer;Gal80 rescue
## HG4: Hsp70-Gal4 killer;Gal80 rescue
## HG4hid: Hsp70-Gal4-hid killer;Gal80 rescue

# choose experiment for parameter estimation
exp <- "G80" #"DG4","HG4","G80", "HG4hid"

library(magrittr)

source('KR_functions.R')

# read in data and manipulate to give genotype fractions
KRdat <- (read.csv("KR_data.csv",header=TRUE))
KRdat <- KRdat[order(KRdat$replicate),]
KRdat$experiment <- factor(KRdat$experiment)
KRdat[,4:10] <- KRdat[,4:10]/KRdat$adults 
KRdat <- KRdat %>% subset(select=-c(adults))

# read in offspring probability array:
# Parray[m,n,i] gives prob of offspring i from mating of female m and male n
# generated by a script but can be calculated by hand
offprobs <- readRDS('offprobs')
Parray <- offprobs[[1]]
genotype_names <- offprobs[[3]]
genotypes <- offprobs[[2]]        

## set input list for simulations and parameter estimation
input <- set_init(exp,genotype_names)
input[["Parray"]] <- Parray

p <- rep(0.9,length(input$pindex)) # initial parameters

dat <- KRdat %>% subset(experiment==exp)
# parameter estimation using Nelder-Mead
sol <- optim(par=transto(p),fn=KR_val_func,input=input,dat=dat,control=list(maxit=2000))
c(sol$convergence,sol$counts)
names(sol$par) <- genotype_names[input$pindex]
paramfit <- transfrom(sol$par)

################## parametric bootstrap

nboot <- 2000
#set input parameters to parameter estimates
input$w[input$pindex] <- paramfit

myseed <- 222
#logfile <- paste0("mylog",myseed,".txt")
#writeLines(c(""),logfile)

library(foreach)
library(doParallel) #can use %do% on a single core without package
library(doRNG)
#cores=detectCores() - 1 # be careful if on hyperthreaded machine or HPC
cores=3
myclust <- makeCluster(cores) #outfile=paste0("clustout",myseed)
registerDoParallel(myclust)
registerDoRNG(myseed)
myout <- foreach(x=iter(1:nboot),.combine=rbind,
                 .packages=c("magrittr")) %dopar% {
                   #cat(paste("Starting iteration", x,"out of", nboot, "at", Sys.time(),"\n"),file=logfile,append=TRUE)
                   fit <- bootfit(input=input)
                   fit
                 }

#cat("Run completed.\n",file=logfile,append=TRUE)
stopCluster(myclust)

attr(myout,"rng") <- NULL
quants <- sapply(colnames(myout),function(x) quantile(myout[,x],probs=c(0.025,0.975)))
quants

mydat <- list(paramfit,myout)

#myfilename <- paste0(exp,myseed)
#saveRDS(mydat,file=paste0(getwd(),myfilename))